// examples/vue-example/src/App.vue
<script setup lang="ts">
import { ref } from 'vue';

const count = ref(0);
</script>

<template>
  <div class="App">
    <h1>Hello Vue</h1>
    <div class="card">
      <button @click="count++">count is {{ count }}</button>
      <p>Edit <code>src/App.vue</code> and save to test HMR</p>
    </div>
  </div>
</template>

<style scoped>
.card {
  padding: 2em;
}
</style>

// examples/react-example/src/App.tsx
import { useState } from 'react';

function App() {
  const [count, setCount] = useState(0);

  return (
    <div className="App">
      <h1>Hello React</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>count is {count}</button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
    </div>
  );
}

export default App;
